# Run all demo notebooks end-to-end (analogous to Python's booktest).
#
# Usage:
#     julia --project=. test/run_notebooks.jl                            # run all
#     julia --project=. test/run_notebooks.jl quickstart                 # run one by name
#     julia --project=. test/run_notebooks.jl --jobs=2                   # shard notebooks
#     julia --project=. test/run_notebooks.jl --shard-count=2 --shard-index=1
#     julia --project=. test/run_notebooks.jl --overwrite=1              # execute with Jupyter and write outputs back
#     julia --project=. test/run_notebooks.jl --overwrite=1 --kernel=quasimc-1.12

using Pkg
getenv_compat(primary::AbstractString, legacy::AbstractString, default::AbstractString="") =
    get(ENV, primary, get(ENV, legacy, default))

const NB_TIMING_TAG = "##QUASIMC_NB_TIMING"
const NB_RESULT_TAG = "##QUASIMC_NB_RESULT"
const NB_TIMING_TAG_LEGACY = "##QMC_NB_TIMING"
const NB_RESULT_TAG_LEGACY = "##QMC_NB_RESULT"

if getenv_compat("QUASIMC_SKIP_PKG_SETUP", "QMC_SKIP_PKG_SETUP", "0") != "1"
    Pkg.resolve()
    Pkg.instantiate()
end

import NBInclude: @nbinclude
using Logging

# NBInclude executes notebook display calls through Base.display, which can hit
# backend-specific rendering assertions in headless CI. Suppress display during
# regression runs so we still execute the plotting code without requiring a GUI.
struct NullNotebookDisplay <: AbstractDisplay end
Base.display(::NullNotebookDisplay, @nospecialize x) = nothing

function with_suppressed_display(f::F) where {F <: Function}
    notebook_display = NullNotebookDisplay()
    pushdisplay(notebook_display)
    try
        return f()
    finally
        popdisplay(notebook_display)
    end
end

Base.@kwdef struct NotebookOptions
    jobs::Int = 1
    shard_count::Int = 1
    shard_index::Int = 1
    overwrite::Bool = false
    kernel::String = "quasimc-1.12"
    timeout::Int = 7200
end

# ── Notebook timing cache (LPT load balancing) ────────────────────────────────
# Each parallel run emits machine-readable timing lines; run_parallel collects
# them and persists per-notebook runtimes here. On the next run split_work_lpt
# uses the saved times to assign notebooks to shards so the slowest shard is
# minimised (Longest Processing Time heuristic).

const NOTEBOOK_TIMES_FILE = joinpath(@__DIR__, "notebook_times.tsv")

function load_notebook_times()::Dict{String, Float64}
    times = Dict{String, Float64}()
    isfile(NOTEBOOK_TIMES_FILE) || return times
    for line in eachline(NOTEBOOK_TIMES_FILE)
        isempty(strip(line)) && continue
        startswith(line, '#') && continue
        parts = split(line, '\t')
        length(parts) == 2 || continue
        try
            times[String(parts[1])] = parse(Float64, parts[2])
        catch
        end
    end
    return times
end

function save_notebook_times(times::Dict{String, Float64})
    open(NOTEBOOK_TIMES_FILE, "w") do io
        println(io, "# Auto-generated by run_notebooks.jl — do not edit by hand.")
        println(io, "# Used for LPT load balancing across parallel shards.")
        println(io, "# notebook_path\telapsed_seconds")
        for nb in sort(collect(keys(times)))
            println(io, "$(nb)\t$(times[nb])")
        end
    end
end

function split_work_lpt(items::Vector{String}, nshards::Int, times::Dict{String, Float64})
    shard_total = max(1, min(nshards, length(items)))
    shards = [String[] for _ in 1:shard_total]
    shard_loads = zeros(shard_total)
    # Unknown notebooks get the 90th-percentile known time so they land in a
    # lightly-loaded shard rather than being treated as trivially fast.
    default_t = if isempty(times)
        60.0
    else
        vals = sort(collect(values(times)))
        vals[max(1, ceil(Int, 0.9 * length(vals)))]
    end
    for nb in sort(items; by=nb2 -> get(times, nb2, default_t), rev=true)
        idx = argmin(shard_loads)
        push!(shards[idx], nb)
        shard_loads[idx] += get(times, nb, default_t)
    end
    return shards
end

function with_updates(
    opts::NotebookOptions;
    jobs::Int=opts.jobs,
    shard_count::Int=opts.shard_count,
    shard_index::Int=opts.shard_index,
    overwrite::Bool=opts.overwrite,
    kernel::String=opts.kernel,
    timeout::Int=opts.timeout,
)
    return NotebookOptions(; jobs, shard_count, shard_index, overwrite, kernel, timeout)
end

# A logger that counts warnings while forwarding them to the console
struct CountingLogger <: AbstractLogger
    inner::ConsoleLogger
    counts::Dict{String, Int}  # notebook name -> warning count
    current_nb::Ref{String}
end

function CountingLogger()
    CountingLogger(ConsoleLogger(stderr, Logging.Warn), Dict{String, Int}(), Ref(""))
end

Logging.min_enabled_level(cl::CountingLogger) = Logging.min_enabled_level(cl.inner)
Logging.shouldlog(cl::CountingLogger, args...) = Logging.shouldlog(cl.inner, args...)
Logging.catch_exceptions(cl::CountingLogger) = Logging.catch_exceptions(cl.inner)

function Logging.handle_message(
    cl::CountingLogger,
    level,
    message,
    _module,
    group,
    id,
    file,
    line;
    kwargs...,
)
    if level >= Logging.Warn
        nb = cl.current_nb[]
        cl.counts[nb] = get(cl.counts, nb, 0) + 1
    end
    Logging.handle_message(cl.inner, level, message, _module, group, id, file, line; kwargs...)
end

# Format a duration in seconds as a short string.
fmt_duration(s::Real) =
    if s >= 60
        m = floor(Int, s / 60)
        return "$(m)m $(round(s - 60m; digits = 1))s"
    else
        return "$(round(s; digits = 2))s"
    end

function parse_args(argv::Vector{String})
    opts = NotebookOptions()
    selectors = String[]
    for arg in argv
        if startswith(arg, "--jobs=")
            raw = split(arg, "="; limit=2)[2]
            jobs = try
                parse(Int, raw)
            catch
                throw(
                    ArgumentError(
                        "invalid --jobs value $(repr(raw)); expected a positive integer",
                    ),
                )
            end
            jobs > 0 || throw(ArgumentError("--jobs must be >= 1, got $jobs"))
            opts = with_updates(opts; jobs)
        elseif startswith(arg, "--shard-count=")
            raw = split(arg, "="; limit=2)[2]
            shard_count = try
                parse(Int, raw)
            catch
                throw(
                    ArgumentError(
                        "invalid --shard-count value $(repr(raw)); expected a positive integer",
                    ),
                )
            end
            shard_count > 0 ||
                throw(ArgumentError("--shard-count must be >= 1, got $shard_count"))
            opts = with_updates(opts; shard_count)
        elseif startswith(arg, "--shard-index=")
            raw = split(arg, "="; limit=2)[2]
            shard_index = try
                parse(Int, raw)
            catch
                throw(
                    ArgumentError(
                        "invalid --shard-index value $(repr(raw)); expected a positive integer",
                    ),
                )
            end
            shard_index > 0 ||
                throw(ArgumentError("--shard-index must be >= 1, got $shard_index"))
            opts = with_updates(opts; shard_index)
        elseif startswith(arg, "--overwrite=")
            raw = lowercase(split(arg, "="; limit=2)[2])
            overwrite =
                raw in ("1", "true", "yes") ? true :
                raw in ("0", "false", "no") ? false :
                throw(
                    ArgumentError(
                        "invalid --overwrite value $(repr(raw)); expected 0/1 or true/false",
                    ),
                )
            opts = with_updates(opts; overwrite)
        elseif startswith(arg, "--kernel=")
            kernel = String(split(arg, "="; limit=2)[2])
            isempty(kernel) && throw(ArgumentError("--kernel must not be empty"))
            opts = with_updates(opts; kernel)
        elseif startswith(arg, "--timeout=")
            raw = split(arg, "="; limit=2)[2]
            timeout = try
                parse(Int, raw)
            catch
                throw(
                    ArgumentError(
                        "invalid --timeout value $(repr(raw)); expected a positive integer",
                    ),
                )
            end
            timeout > 0 || throw(ArgumentError("--timeout must be >= 1, got $timeout"))
            opts = with_updates(opts; timeout)
        else
            push!(selectors, arg)
        end
    end
    opts.shard_index <= opts.shard_count || throw(
        ArgumentError(
            "--shard-index must be <= --shard-count; got $(opts.shard_index) > $(opts.shard_count)",
        ),
    )
    return opts, selectors
end

function select_notebooks(all_notebooks::Vector{String}, selectors::Vector{String})
    isempty(selectors) && return all_notebooks
    selected = String[]
    seen = Set{String}()
    for selector in selectors
        matches =
            endswith(selector, ".ipynb") ? filter(nb -> nb == selector, all_notebooks) :
            filter(nb -> occursin(selector, nb), all_notebooks)
        if isempty(matches)
            throw(ArgumentError("no notebook matching $(repr(selector)) found in demos/"))
        end
        for notebook in matches
            if notebook ∉ seen
                push!(selected, notebook)
                push!(seen, notebook)
            end
        end
    end
    return selected
end

function split_work(items::Vector{String}, nshards::Int; allow_empty::Bool=false)
    nshards > 0 || throw(ArgumentError("number of shards must be >= 1, got $nshards"))
    shard_total = allow_empty ? nshards : max(1, min(nshards, length(items)))
    shards = [String[] for _ in 1:shard_total]
    isempty(items) && return shards
    for (idx, item) in enumerate(items)
        push!(shards[1 + mod(idx - 1, shard_total)], item)
    end
    return shards
end

function select_shard(notebooks::Vector{String}, opts::NotebookOptions)
    opts.shard_count == 1 && return notebooks
    shards = split_work(notebooks, opts.shard_count; allow_empty=true)
    selected = shards[opts.shard_index]
    println(
        "Selected notebook shard $(opts.shard_index)/$(opts.shard_count): " *
        "$(length(selected)) of $(length(notebooks)) notebook(s).",
    )
    return selected
end

function current_project_dir()
    active_project = Base.active_project()
    active_project === nothing && return dirname(@__DIR__)
    return dirname(active_project)
end

function child_cmd(notebooks::Vector{String}, opts::NotebookOptions)
    script = joinpath(@__DIR__, "run_notebooks.jl")
    base_argv = collect(Base.julia_cmd())
    argv = vcat(
        base_argv,
        [
            script,
            "--jobs=1",
            "--overwrite=$(Int(opts.overwrite))",
            "--kernel=$(opts.kernel)",
            "--timeout=$(opts.timeout)",
        ],
        notebooks,
    )
    cmd = Cmd(argv)
    return addenv(
        cmd,
        "JULIA_PROJECT" => current_project_dir(),
        "JULIA_NUM_THREADS" => string(Threads.nthreads()),
        "QUASIMC_SKIP_PKG_SETUP" => "1",
        "QUASIMC_NOTEBOOK_VERBOSE" =>
            getenv_compat("QUASIMC_NOTEBOOK_VERBOSE", "QMC_NOTEBOOK_VERBOSE", "0"),
    )
end

Base.@kwdef mutable struct ShardRun
    idx::Int
    count::Int
    notebooks::Vector{String}
    log_path::String
    task::Task
    started_at::Float64 = time()
    last_pos::Int = 0
    last_output_at::Float64 = time()
    last_heartbeat_at::Float64 = 0.0
    announced::Bool = false
end

function start_child_shard(
    notebooks::Vector{String},
    shard_idx::Int,
    shard_count::Int,
    opts::NotebookOptions,
)
    log_path, io = mktemp()
    close(io)
    task = @async begin
        ok = false
        elapsed = @elapsed begin
            open(log_path, "w") do log_io
                proc = run(
                    pipeline(
                        ignorestatus(child_cmd(notebooks, opts)),
                        stdout=log_io,
                        stderr=log_io,
                    ),
                )
                ok = success(proc)
            end
        end
        return (
            idx=shard_idx,
            count=shard_count,
            notebooks=notebooks,
            ok=ok,
            log_path=log_path,
            elapsed=elapsed,
        )
    end
    return ShardRun(; idx=shard_idx, count=shard_count, notebooks, log_path, task)
end

function announce_shard!(shard::ShardRun)
    shard.announced && return
    println()
    println("[notebook shard $(shard.idx)/$(shard.count)] " * "$(join(shard.notebooks, ", "))")
    shard.announced = true
end

function drain_shard_output!(shard::ShardRun)
    ispath(shard.log_path) || return false
    filesize(shard.log_path) > shard.last_pos || return false
    announce_shard!(shard)
    open(shard.log_path, "r") do io
        seek(io, shard.last_pos)
        chunk = read(io, String)
        if !isempty(chunk)
            # Strip machine-readable timing lines before echoing to the console.
            visible = filter(
                ln ->
                    !startswith(ln, NB_TIMING_TAG) && !startswith(ln, NB_TIMING_TAG_LEGACY),
                split(chunk, '\n'; keepempty=true),
            )
            filtered = join(visible, '\n')
            if !isempty(strip(filtered))
                print(filtered)
                endswith(filtered, '\n') || println()
            end
            shard.last_pos = position(io)
            shard.last_output_at = time()
            return true
        end
    end
    return false
end

function maybe_print_shard_heartbeat!(shard::ShardRun; interval::Real=30)
    istaskdone(shard.task) && return
    now = time()
    since_output = now - shard.last_output_at
    since_heartbeat = shard.last_heartbeat_at == 0.0 ? Inf : now - shard.last_heartbeat_at
    if since_output >= interval && since_heartbeat >= interval
        announce_shard!(shard)
        println(
            "  ... still running after $(fmt_duration(now - shard.started_at)) " *
            "($(length(shard.notebooks)) notebook(s))",
        )
        shard.last_heartbeat_at = now
    end
end

function notebook_python()
    py = getenv_compat("QUASIMC_NOTEBOOK_PYTHON", "QMC_NOTEBOOK_PYTHON", "")
    return isempty(py) ? "python3" : py
end

function notebook_jupyter()
    py = notebook_python()
    sibling = joinpath(dirname(py), "jupyter")
    return isfile(sibling) ? sibling : "jupyter"
end

function run_one_notebook_inplace(
    nb::String,
    demos_dir::AbstractString,
    kernel::AbstractString,
    timeout::Int,
)
    print("Executing ", nb, " with kernel ", kernel, " ... ")
    notebook_path = joinpath(demos_dir, nb)
    captured = ""
    failed = false
    err_text = ""
    elapsed = @elapsed try
        mktempdir() do ipython_dir
            mktemp() do _, io
                cmd = Cmd([
                    notebook_jupyter(),
                    "nbconvert",
                    "--to",
                    "notebook",
                    "--execute",
                    "--inplace",
                    "--ExecutePreprocessor.kernel_name=$(kernel)",
                    "--ExecutePreprocessor.timeout=$(timeout)",
                    basename(notebook_path),
                ],)
                cmd = Cmd(cmd; dir=dirname(notebook_path))
                proc = run(
                    pipeline(
                        ignorestatus(addenv(cmd, "IPYTHONDIR" => ipython_dir)),
                        stdout=io,
                        stderr=io,
                    ),
                )
                flush(io)
                seekstart(io)
                captured = read(io, String)
                success(proc) || error("nbconvert exited with code $(proc.exitcode)")
            end
        end
    catch e
        failed = true
        err_text = sprint(io -> showerror(io, e, catch_backtrace()))
    end

    if failed
        println("FAILED")
        if !isempty(strip(captured))
            println("---- captured nbconvert output ----")
            print(captured)
            endswith(captured, '\n') || println()
            println("---- end captured nbconvert output ----")
        end
        println("  x FAILED: ", err_text)
        println("  time: ", fmt_duration(elapsed))
        return false, elapsed, 0
    end

    println("ok [$(fmt_duration(elapsed))]")
    return true, elapsed, 0
end

function run_one_notebook(
    nb::String,
    demos_dir::AbstractString,
    clogger::CountingLogger,
    verbose::Bool,
    timeout::Int,
)
    print("Running ", nb, " ... ")
    # Execute the notebook in a *child process* and enforce the timeout by
    # killing that process. The previous in-process approach used
    # `Threads.@spawn` + `schedule(task, InterruptException())`, which cannot
    # interrupt a task blocked inside a native `ccall` (e.g. the qmctoolscl C
    # library that backs `gen_samples`). When such a call ran long, the soft
    # timeout never fired and CI hung until the GitHub step timeout cancelled
    # the whole job. Killing the process always works.
    cmd = addenv(
        Cmd(vcat(collect(Base.julia_cmd()), [joinpath(@__DIR__, "run_notebooks.jl")])),
        "JULIA_PROJECT" => current_project_dir(),
        "JULIA_NUM_THREADS" => string(Threads.nthreads()),
        "QUASIMC_SKIP_PKG_SETUP" => "1",
        "QUASIMC_NB_ONE" => nb,
        "QUASIMC_NOTEBOOK_VERBOSE" => verbose ? "1" : "0",
    )
    buf = IOBuffer()
    proc = run(pipeline(ignorestatus(cmd); stdout=buf, stderr=buf); wait=false)
    failed = false
    err_text = ""
    elapsed = @elapsed begin
        if timedwait(() -> process_exited(proc), float(timeout); pollint=1.0) == :timed_out
            kill(proc)                                   # SIGTERM
            if timedwait(() -> process_exited(proc), 10.0; pollint=0.5) == :timed_out
                kill(proc, 9)                            # SIGKILL
            end
            wait(proc)
            failed = true
            err_text = "timed out after $(fmt_duration(timeout)) (process killed)"
        else
            failed = !success(proc)
            failed && (err_text = "notebook process exited with code $(proc.exitcode)")
        end
    end

    # The child appends a machine-readable result line; parse and strip it so
    # warning counts still feed the run summary.
    warnings = 0
    kept = String[]
    for ln in split(String(take!(buf)), '\n')
        m = match(r"^##(?:QUASIMC|QMC)_NB_RESULT ok=(\w+) warnings=(\d+)$", ln)
        if m === nothing
            push!(kept, ln)
        else
            m.captures[1] == "false" && (failed = true)
            warnings = parse(Int, m.captures[2])
        end
    end
    captured = join(kept, '\n')

    if failed
        println("FAILED")
        if !isempty(strip(captured))
            println("---- captured notebook output ----")
            print(captured)
            endswith(captured, '\n') || println()
            println("---- end captured output ----")
        end
        isempty(err_text) && (err_text = "notebook failed")
        println("  x FAILED: ", err_text)
        println("  time: ", fmt_duration(elapsed))
        println("$(NB_TIMING_TAG)\t$(nb)\t$(round(elapsed; digits=3))")
        return false, elapsed, warnings
    end

    wtxt = warnings > 0 ? ", $warnings warning(s)" : ""
    println("ok [$(fmt_duration(elapsed))]$wtxt")
    # Machine-readable timing consumed by run_parallel to build the LPT timing cache.
    println("$(NB_TIMING_TAG)\t$(nb)\t$(round(elapsed; digits=3))")
    return true, elapsed, warnings
end

function run_serial(notebooks::Vector{String}, demos_dir::AbstractString, opts::NotebookOptions)
    times = Dict{String, Float64}()
    warnings_by_notebook = Dict{String, Int}()
    errors = String[]
    clogger = CountingLogger()
    verbose = getenv_compat("QUASIMC_NOTEBOOK_VERBOSE", "QMC_NOTEBOOK_VERBOSE", "0") == "1"

    for nb in notebooks
        ok, elapsed, warnings =
            opts.overwrite ?
            run_one_notebook_inplace(nb, demos_dir, opts.kernel, opts.timeout) :
            run_one_notebook(nb, demos_dir, clogger, verbose, opts.timeout)
        times[nb] = elapsed
        warnings_by_notebook[nb] = warnings
        ok || push!(errors, nb)
        GC.gc()
    end

    total_warnings = sum(values(warnings_by_notebook); init=0)
    total_time = sum(values(times); init=0.0)
    n_pass = length(notebooks) - length(errors)

    println("\n", "="^60)
    println("Summary")
    println("="^60)
    for nb in errors
        w = get(warnings_by_notebook, nb, 0)
        t = get(times, nb, 0.0)
        wtxt = w > 0 ? ", $w warning(s)" : ""
        println("  x FAILED  $nb  [$(fmt_duration(t))]$wtxt")
    end
    println("-"^60)
    println(
        "Ran $(length(notebooks)) notebook(s): $(n_pass) passed, $(length(errors)) failed, " *
        "$(total_warnings) warning(s) in $(fmt_duration(total_time)).",
    )

    if !isempty(errors)
        exit(1)
    else
        println("All notebooks passed.")
    end
end

function run_parallel(notebooks::Vector{String}, opts::NotebookOptions)
    times = load_notebook_times()
    shard_notebooks = if !isempty(times)
        coverage = count(nb -> haskey(times, nb), notebooks)
        println(
            "LPT scheduling: $(coverage)/$(length(notebooks)) notebook(s) have timing data.",
        )
        split_work_lpt(notebooks, opts.jobs, times)
    else
        split_work(notebooks, opts.jobs)
    end
    println(
        "Running $(length(notebooks)) notebook(s) across $(length(shard_notebooks)) " *
        "parallel shard(s)...",
    )
    wall = @elapsed begin
        shards = [
            start_child_shard(shard, idx, length(shard_notebooks), opts) for
            (idx, shard) in enumerate(shard_notebooks)
        ]
        while any(!istaskdone(shard.task) for shard in shards)
            for shard in shards
                drain_shard_output!(shard)
                maybe_print_shard_heartbeat!(shard)
            end
            sleep(1)
        end
        results = map(fetch, getfield.(shards, :task))
        # Collect per-notebook timings from shard logs before cleanup, then
        # persist them so the next run can use LPT scheduling.
        all_times = load_notebook_times()
        failed = false
        for (shard, result) in zip(shards, results)
            drain_shard_output!(shard)
            failed |= !result.ok
            try
                for line in eachline(result.log_path)
                    parts = split(line, '\t')
                    if length(parts) == 3 &&
                       (parts[1] == NB_TIMING_TAG || parts[1] == NB_TIMING_TAG_LEGACY)
                        all_times[String(parts[2])] = parse(Float64, parts[3])
                    end
                end
            catch
            end
            rm(result.log_path; force=true)
        end
        save_notebook_times(all_times)
        println()
        println("Parallel shard summary")
        println("-"^60)
        for result in results
            status = result.ok ? "passed" : "FAILED"
            println(
                "  shard $(result.idx)/$(result.count): $status " *
                "($(length(result.notebooks)) notebook(s), $(fmt_duration(result.elapsed)))",
            )
        end
        if failed
            println("-"^60)
            println("One or more notebook shards failed; see shard logs above.")
            exit(1)
        end
    end
    println()
    println(
        "Completed parallel notebook run for $(length(notebooks)) notebook(s) in " *
        "$(fmt_duration(wall)).",
    )
end

function collect_notebooks(demos_dir::AbstractString)
    notebooks = String[]
    for (root, _, files) in walkdir(demos_dir)
        rel_root = relpath(root, demos_dir)
        path_parts =
            rel_root == "." ? String[] : split(rel_root, Base.Filesystem.path_separator)
        any(startswith(part, ".") for part in path_parts) && continue
        for file in files
            endswith(file, ".ipynb") || continue
            startswith(file, ".") && continue
            endswith(file, "-checkpoint.ipynb") && continue
            push!(notebooks, relpath(joinpath(root, file), demos_dir))
        end
    end
    return sort(notebooks)
end

demos_dir = joinpath(@__DIR__, "..", "demos")

# Child mode: execute exactly one notebook in-process and exit. The parent
# (`run_one_notebook`) launches this with QUASIMC_NB_ONE set and enforces the
# per-notebook timeout by killing the process — the only reliable way to stop a
# notebook stuck inside a native `ccall` (e.g. qmctoolscl).
if haskey(ENV, "QUASIMC_NB_ONE") || haskey(ENV, "QMC_NB_ONE")
    # `let` keeps these names local so the `one_ok` assignment in the `catch`
    # below is unambiguous; at global scope it would trip a soft-scope warning.
    let one_nb = getenv_compat("QUASIMC_NB_ONE", "QMC_NB_ONE"),
        one_clog = CountingLogger(),
        one_ok = true

        one_clog.current_nb[] = one_nb
        try
            with_suppressed_display() do
                with_logger(one_clog) do
                    @nbinclude(joinpath(demos_dir, one_nb))
                end
            end
        catch e
            one_ok = false
            showerror(stderr, e, catch_backtrace())
            println(stderr)
        end
        flush(stdout)
        flush(stderr)
        println("$(NB_RESULT_TAG) ok=$(one_ok) warnings=$(get(one_clog.counts, one_nb, 0))")
        exit(one_ok ? 0 : 1)
    end
end

all_notebooks = collect_notebooks(demos_dir)
opts, selectors = parse_args(ARGS)
notebooks = select_shard(select_notebooks(all_notebooks, selectors), opts)

if opts.jobs == 1 || length(notebooks) <= 1
    run_serial(notebooks, demos_dir, opts)
else
    run_parallel(notebooks, opts)
end
