"""
    BrownianMotion(dd::AbstractDiscreteDistribution; time_vector=nothing, drift=0.0)

Brownian motion measure. The dimension of `dd` determines the number of time
steps. Samples are generated by constructing a Gaussian measure whose covariance
is the Brownian motion covariance `C[i,j] = min(t[i], t[j])`, applying a PCA
decomposition, and optionally adding a linear drift.

# Arguments
- `dd`: a discrete distribution providing uniform samples in [0,1)^d, where `d`
  is the number of time steps.
- `time_vector`: d-vector of increasing positive times. Default is
  `[1/d, 2/d, ..., 1]`.
- `drift`: scalar drift coefficient. The drift contribution at time `t[j]` is
  `drift * t[j]`. Default `0.0`.

# Examples
```julia
dd = IIDStdUniform(64; seed=7)
bm = BrownianMotion(dd; drift=0.05)
x = gen_samples(dd, 256)
paths = transform(bm, x)  # 256×64 Brownian motion paths
```
"""
struct BrownianMotion <: AbstractTrueMeasure
    dd::AbstractDiscreteDistribution
    dimension::Int
    time_vector::Vector{Float64}
    drift::Float64
    _gaussian::Gaussian
end

function BrownianMotion(dd::AbstractDiscreteDistribution;
        time_vector = nothing, drift = 0.0)
    d = dd.dimension
    if isnothing(time_vector)
        tv = collect(range(1.0 / d, 1.0; length = d))
    else
        tv = Float64.(collect(time_vector))
        length(tv) == d ||
            throw(ArgumentError("time_vector length ($(length(tv))) must match dimension ($d)"))
        issorted(tv; lt = <=) ||
            throw(ArgumentError("time_vector must be strictly increasing"))
        all(tv .> 0) || throw(ArgumentError("time_vector entries must be positive"))
    end
    # Build Brownian motion covariance: C[i,j] = min(t[i], t[j])
    cov = _bm_covariance(tv)
    # Internal Gaussian with zero mean and BM covariance (PCA decomposition)
    gauss = Gaussian(dd; mean = 0.0, covariance = cov, decomp_type = :PCA)
    return BrownianMotion(dd, d, tv, Float64(drift), gauss)
end

"""Build the d×d covariance matrix for Brownian motion: C[i,j] = min(t[i], t[j])."""
function _bm_covariance(t::Vector{Float64})
    d = length(t)
    C = Matrix{Float64}(undef, d, d)
    @inbounds for j in 1:d
        for i in 1:d
            C[i, j] = min(t[i], t[j])
        end
    end
    return C
end

function transform(tm::BrownianMotion, x::AbstractMatrix)
    # Gaussian transform gives zero-mean BM paths
    y = transform(tm._gaussian, x)
    # Add drift: drift * t for each time step
    if tm.drift != 0.0
        y .+= tm.drift .* tm.time_vector'
    end
    return y
end

function Base.show(io::IO, tm::BrownianMotion)
    print(io,
        "BrownianMotion(d=$(tm.dimension), drift=$(tm.drift), t=[$(tm.time_vector[1]),…,$(tm.time_vector[end])])")
end
