"""
    BrownianMotion(dd::AbstractDiscreteDistribution; time_vector=nothing, t_final=nothing,
                   drift=0.0, initial_value=0.0, diffusion=1.0, decomp_type=:PCA)

Brownian motion measure. The dimension of `dd` determines the number of time
steps. Samples are generated by constructing a Gaussian measure whose covariance
is the (diffusion-scaled) Brownian motion covariance
`Cov[i,j] = diffusion * min(t[i], t[j])`, decomposing it (`:PCA` or `:Cholesky`),
and adding the deterministic mean `initial_value + drift * t[j]`.

# Arguments
- `dd`: a discrete distribution providing uniform samples in [0,1)^d, where `d`
  is the number of time steps.
- `time_vector`: d-vector of increasing positive times. Mutually exclusive with
  `t_final`.
- `t_final`: final time `T`; the grid becomes `[T/d, 2T/d, ..., T]` (QMCPy's
  convention). Defaults (with no `time_vector`) to `T = 1`, i.e. `[1/d, ..., 1]`.
- `drift`: scalar drift coefficient; the drift contribution at `t[j]` is
  `drift * t[j]`. Default `0.0`.
- `initial_value`: constant added to every path (the value at `t = 0`). Default
  `0.0`.
- `diffusion`: positive variance rate scaling the covariance. Default `1.0`.
- `decomp_type`: covariance decomposition, `:PCA` (default) or `:Cholesky`.

# Examples
```jldoctest
julia> using QMC

julia> bm = BrownianMotion(DigitalNetB2(4; seed=7); t_final=2.0, drift=2.0)
BrownianMotion(d=4, drift=2.0, initial_value=0.0, diffusion=1.0, t=[0.5,…,2.0])

julia> x = gen_samples(bm.dd, 2);

julia> round.(transform(bm, x); digits=6)
2×4 Matrix{Float64}:
 -0.150693  1.30827  1.56816  1.95239
  0.61333   1.47243  3.29425  4.92554
```
"""
struct BrownianMotion{D <: AbstractDiscreteDistribution, G <: Gaussian} <: AbstractTrueMeasure
    dd::D
    dimension::Int
    time_vector::Vector{Float64}
    drift::Float64
    initial_value::Float64
    diffusion::Float64
    _gaussian::G
end

function BrownianMotion(
    dd::AbstractDiscreteDistribution;
    time_vector=nothing,
    t_final=nothing,
    drift=0.0,
    initial_value=0.0,
    diffusion=1.0,
    decomp_type::Symbol=:PCA,
)
    d = dimension(dd)
    diffusion > 0 || throw(ArgumentError("diffusion must be positive"))
    if !isnothing(time_vector) && !isnothing(t_final)
        throw(ArgumentError("supply either time_vector or t_final, not both"))
    end
    if !isnothing(time_vector)
        tv = Float64.(collect(time_vector))
        length(tv) == d ||
            throw(ArgumentError("time_vector length ($(length(tv))) must match dimension ($d)"))
        issorted(tv; lt=<=) || throw(ArgumentError("time_vector must be strictly increasing"))
        all(tv .> 0) || throw(ArgumentError("time_vector entries must be positive"))
    elseif !isnothing(t_final)
        t_final > 0 || throw(ArgumentError("t_final must be positive"))
        tv = collect(range(Float64(t_final) / d, Float64(t_final); length=d))
    else
        tv = collect(range(1.0 / d, 1.0; length=d))
    end
    # Brownian motion covariance scaled by the diffusion coefficient:
    # Cov[i,j] = diffusion * min(t[i], t[j]).
    cov = diffusion .* _bm_covariance(tv)
    # Internal zero-mean Gaussian with the BM covariance; the deterministic mean
    # (initial_value + drift*t) is added in `transform`.
    gauss = Gaussian(dd; mean=0.0, covariance=cov, decomp_type=decomp_type)
    return BrownianMotion(
        dd,
        d,
        tv,
        Float64(drift),
        Float64(initial_value),
        Float64(diffusion),
        gauss,
    )
end

"""Build the d×d covariance matrix for Brownian motion: C[i,j] = min(t[i], t[j])."""
function _bm_covariance(t::Vector{Float64})
    d = length(t)
    C = Matrix{Float64}(undef, d, d)
    @inbounds for j in 1:d
        for i in 1:d
            C[i, j] = min(t[i], t[j])
        end
    end
    return C
end

function transform(tm::BrownianMotion, x::AbstractMatrix)
    # Gaussian transform gives zero-mean, diffusion-scaled BM paths
    y = transform(tm._gaussian, x)
    # Add the deterministic mean: initial_value + drift * t at each time step.
    if tm.initial_value != 0.0 || tm.drift != 0.0
        y .+= (tm.initial_value .+ tm.drift .* tm.time_vector)'
    end
    return y
end

function Base.show(io::IO, tm::BrownianMotion)
    print(
        io,
        "BrownianMotion(d=$(tm.dimension), drift=$(tm.drift), initial_value=$(tm.initial_value), diffusion=$(tm.diffusion), t=[$(tm.time_vector[1]),…,$(tm.time_vector[end])])",
    )
end
